### ISSUE TITLE
Kill session

### ISSUE THREAD

**Issue by leebaird** [DeveloperShed/BasicSecureLogin#4]
This is the textbook way to kill a session:

```
if (ini_get("session.use_cookies")) {
    $params = session_get_cookie_params();
    setcookie(session_name(), '', time() - 42000,
        $params["path"], $params["domain"],
        $params["secure"], $params["httponly"]
    );
}

session_destroy();
```

**Comment by Nilpo** [comment]
This is a good suggestion. However, you also need to unset all session variables. I also really like the comments from the [PHP manual](http://php.net/manual/en/function.session-destroy.php).

```
// Unset all of the session variables.
$_SESSION = array();

// If it's desired to kill the session, also delete the session cookie.
// Note: This will destroy the session, and not just the session data!
if (ini_get("session.use_cookies")) {
    $params = session_get_cookie_params();
    setcookie(session_name(), '', time() - 42000,
        $params["path"], $params["domain"],
        $params["secure"], $params["httponly"]
    );
}

// Finally, destroy the session.
session_destroy();
```

If you submit a pull request, I will add this. This is an important practice for others to learn.

**Comment by Nilpo** [comment]
I've relabeled this as an enhancement instead of a bug. There may be some instances when removing the session is not desirable when logging out such as when you don't wish to lose the contents of a shopping cart.
